### ISSUE TITLE
Review and automate checking of dependencies

### ISSUE THREAD

**Issue by thec00n** [omisego/react-starter-kit#34]
### Description
As discussed it is recommended to review the dependencies in package.json and to remove anything that is not strictly required. Further let's use `npm audit` in our CI to check for dependencies that have vulnerabilities.

**Comment by nicholasmueller** [comment]
https://github.com/omisego/security-issues/issues/21

**Comment by nicholasmueller** [comment]
resolved -> https://github.com/omisego/react-starter-kit/commit/98795820cd512286d3d6873e65e12cb06c741807
